sonar.projectKey=lautiod_TP8_ContenedoresAutomatizacion
sonar.organization=lautiod

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=TP8_ContenedoresAutomatizacion
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=EmployeeCrudApi/EmployeeCrudApi,EmployeeCrudAngular/src
sonar.tests=EmployeeCrudApi.Tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/bin/**,**/obj/**,**/*.spec.ts

# Coverage exclusions
sonar.coverage.exclusions=**/test/**,**/*.spec.ts,**/Program.cs

# Language specific properties
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.javascript.lcov.reportPaths=EmployeeCrudAngular/coverage/lcov.info
