# ===== Build Angular (Production) =====
FROM node:20 AS build
WORKDIR /app

# Copio package* primero para aprovechar cache
COPY EmployeeCrudAngular/package*.json ./
RUN npm install

# Copio el resto del código y build production
COPY EmployeeCrudAngular/ ./
RUN npx ng build --configuration production

# ===== Nginx para servir estático =====
FROM nginx:alpine AS final

# Quita el default y pone uno SPA-friendly (maneja rutas)
COPY EmployeeCrudAngular/nginx.conf /etc/nginx/conf.d/default.conf

# Copio el artefacto Angular (Angular 17+ usa /browser)
COPY --from=build /app/dist/employee-crud-angular/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
